### ISSUE TITLE
mac OS X Catalina で seedtable-egui.app が動かない

### ISSUE THREAD

**Issue by yoshitetsu** [seed-ui/seedtable#66]
seedフォルダや設定の「開く」ボタンで指定すると下記のようなエラーが出る状況です。

![image](https://user-images.githubusercontent.com/9644/79978777-6a0a8500-84db-11ea-9769-485225f5e4d5.png)

#  実行環境
- OS: mac OS X Catalina
- seedtable-egui v4.0.0

**Comment by Narazaka** [comment]
クソOSことCatalina……

**Comment by Narazaka** [comment]
@yoshitetsu @junjanjon 
xcode11.5でビルドした版を作ってみましたが動きますかね？
https://github.com/seed-ui/seedtable/releases/tag/v4.0.1

**Comment by Narazaka** [comment]
というかMacはメンテナが欲しい

**Comment by yoshitetsu** [comment]
@Narazaka 
ありがとうございます。Catalinaで動作確認できましたのでissueのcloseをお願いします。
これで非エンジニアの方も助かります。

**Comment by Narazaka** [comment]
@yoshitetsu お、ありがとうございます。closeします。
